"""
Populate 90_Day_Master_Plan Google Sheet
-----------------------------------------
Creates the main tab and meta tab, then fills in a full 90-day
AI/ML curriculum (RAG → Agents → Evaluation → Deployment).

Run once:
    python execution/populate_mentor_sheet.py
"""

import os
import sys
import json
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent / ".env")

import gspread
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/calendar.events",
]

ROOT = Path(__file__).resolve().parent
CREDENTIALS_FILE = str(ROOT / "credentials.json")
TOKEN_FILE = str(ROOT / "token.json")
SHEET_ID = os.getenv("GOOGLE_SHEET_ID")


def get_credentials():
    creds = None
    if os.path.exists(TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(CREDENTIALS_FILE, SCOPES)
            creds = flow.run_local_server(port=0)
        with open(TOKEN_FILE, "w") as f:
            f.write(creds.to_json())
    return creds


# ── 90-Day Curriculum ─────────────────────────────────────────────────────────
# Columns: Phase, Week, Day, Topic, Core Task, Secondary Reading,
#          Reflection Prompt, Difficulty Level, Status, Notes,
#          Commit Link, Streak, Weekly Score

HEADERS = [
    "Phase", "Week", "Day", "Topic", "Core Task",
    "Secondary Reading", "Reflection Prompt",
    "Difficulty Level", "Layer", "Artifact Produced",
    "Status", "Notes", "Commit Link", "Streak", "Weekly Score",
    "Measured Metric", "Failure Mode Found", "Tradeoff Identified",
    "Reusability Score", "Paper Read", "Key Insight"
]

CURRICULUM = [
    ['Phase 1: RAG Foundations', 1, 1, 'Environment Setup', 'Set up Python venv, install LangChain + ChromaDB, ingest 10 docs, run first RAG query', 'https://python.langchain.com/docs/get_started/introduction | https://arxiv.org/abs/2005.11401', 'What does retrieval quality fundamentally depend on?', 2, 'System', 'Working RAG pipeline + 10-doc corpus', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 1: RAG Foundations', 1, 2, 'Chunking Strategies', 'Implement fixed-size, sentence, and recursive chunking. Compare retrieval quality across strategies on 50 docs', 'https://www.pinecone.io/learn/chunking-strategies/', 'Why does chunk size affect answer quality differently for short vs long queries?', 2, 'System', 'Chunking comparison report (3 strategies)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 1: RAG Foundations', 1, 3, 'Embedding Models', 'Benchmark 3 embedding models (OpenAI, BGE, Cohere) on the same corpus. Log top-5 retrieval accuracy', 'https://huggingface.co/blog/mteb | https://arxiv.org/abs/2004.04906', 'What tradeoffs exist between embedding model size and retrieval speed?', 3, 'Model', 'Embedding benchmark results (3 models)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 1: RAG Foundations', 1, 4, 'Vector Store Comparison', 'Set up ChromaDB and FAISS side-by-side. Run 100 queries, compare latency and accuracy', 'https://docs.trychroma.com/getting-started', 'When would you choose an in-memory store over a persistent one?', 3, 'Infra', 'Vector store comparison report (ChromaDB vs FAISS)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 1: RAG Foundations', 1, 5, 'Metadata Filtering', 'Add date, source, and category metadata to chunks. Implement filtered retrieval and test 10 filter combinations', 'https://python.langchain.com/docs/modules/data_connection/retrievers/', 'How does metadata filtering change the role of semantic similarity?', 3, 'System', 'Filtered retrieval module', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 1: RAG Foundations', 1, 6, 'Retrieval Evaluation', 'Implement MRR@10 and Hit Rate@5 metrics. Score your RAG pipeline on 20 hand-labelled QA pairs', 'https://docs.ragas.io/en/stable/concepts/metrics/', "What does MRR tell you that accuracy alone doesn't?", 3, 'Evaluation', 'MRR@10 + Hit Rate evaluation script', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 1: RAG Foundations', 1, 7, 'Week 1 Review + Micro Project', "Write 500-word reflection (what broke, what you'd redo, what metric improved most). WEEK 1 MICRO PROJECT: Ship 'Embedding Benchmark CLI' — a reusable Python tool that benchmarks 3 embedding models on a user-supplied corpus, outputs a JSON/CSV report, and has a full README. Push to public GitHub repo.", 'https://eugeneyan.com/writing/llm-patterns/', 'What was your single biggest assumption that turned out to be wrong?', 2, 'Product', 'Embedding Benchmark CLI (public repo)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 1: RAG Foundations', 2, 8, 'Threshold Sweep', 'Implement similarity threshold sweep from 0.4–0.9 in steps of 0.1. Plot precision-recall tradeoff', 'https://www.sbert.net/docs/usage/semantic_textual_similarity.html', 'At what threshold does precision start to degrade faster than recall improves?', 3, 'Evaluation', 'Threshold sweep plot (precision-recall)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 1: RAG Foundations', 2, 9, 'Hybrid Search', 'Implement BM25 + dense vector hybrid search using RRF fusion. Compare vs pure dense on 50 queries', 'https://arxiv.org/abs/2009.09225', 'What types of queries benefit most from keyword search vs semantic search?', 4, 'System', 'Hybrid search module (BM25+dense RRF)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 1: RAG Foundations', 2, 10, 'Query Rewriting', 'Build HyDE (Hypothetical Document Embeddings) query expansion. Measure improvement on ambiguous queries', 'https://arxiv.org/abs/2212.10496', 'Why might a hypothetical answer be a better search query than the original question?', 4, 'Model', 'HyDE query expansion module', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 1: RAG Foundations', 2, 11, 'Reranking', 'Add a cross-encoder reranker (ms-marco-MiniLM). Compare NDCG@5 before and after reranking', 'https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2 | https://arxiv.org/abs/2004.12832', 'What computational tradeoff does a reranker introduce and when is it worth it?', 4, 'Model', 'Reranker integration + NDCG comparison', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 1: RAG Foundations', 2, 12, 'Context Window Management', 'Implement context stuffing, map-reduce, and refine chain patterns. Test on 5 multi-doc questions', 'https://python.langchain.com/docs/use_cases/question_answering/', 'How does context ordering affect LLM answer quality?', 3, 'System', 'Context chain patterns (3 strategies)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 1: RAG Foundations', 2, 13, 'Prompt Engineering for RAG', 'Write 5 system prompt variants with different instruction styles. A/B test answer quality using GPT-4-as-judge', 'https://www.promptingguide.ai/techniques/rag', 'What makes a RAG system prompt different from a general chatbot prompt?', 3, 'Model', '5 prompt variants + A/B test results', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 1: RAG Foundations', 2, 14, 'Week 2 Review + System Design', "Build mini benchmark dashboard (Streamlit) for Weeks 1-2 metrics. SYSTEM DESIGN CHALLENGE: Design ChatGPT at scale — whiteboard it, then write a 1-page architecture doc covering retrieval, caching, load balancing, and cost-per-query at 1M users. Push doc to repo. MICRO PROJECT: Ship 'Hybrid Search Package' — pip-installable BM25+dense RRF fusion module.", 'https://docs.streamlit.io/get-started', 'Which metric moved the needle most — retrieval quality or generation quality?', 2, 'Product', 'Hybrid Search Package (pip-installable) + Streamlit dashboard', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 2: Agentic AI', 3, 15, 'ReAct Pattern', 'Implement a ReAct agent from scratch (no framework). Build: search + calculator + code tools', 'https://arxiv.org/abs/2210.03629', "What failure modes does ReAct have that pure chain-of-thought doesn't?", 3, 'System', 'ReAct agent (from scratch, no framework)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 2: Agentic AI', 3, 16, 'Tool Use & Function Calling', 'Build 5 custom tools using OpenAI function calling. Implement retry logic for tool failures', 'https://platform.openai.com/docs/guides/function-calling | https://arxiv.org/abs/2302.04761', 'How should an agent handle a tool that returns an error vs one that returns empty results?', 3, 'System', '5 custom tools with retry logic', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 2: Agentic AI', 3, 17, 'Memory Systems', 'Implement episodic (conversation buffer), semantic (vector memory), and procedural memory in one agent', 'https://python.langchain.com/docs/modules/memory/', "When should an agent forget? What's the cost of never forgetting?", 4, 'System', '3-type memory system module', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 2: Agentic AI', 3, 18, 'Planning & Decomposition', 'Implement task decomposition using LLM planner + executor pattern. Test on 3 multi-step research tasks', 'https://arxiv.org/abs/2305.10601', 'How do you know when a task is decomposed enough vs over-decomposed?', 4, 'System', 'Task decomposition planner', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 2: Agentic AI', 3, 19, 'Multi-Agent Coordination', 'Build a 3-agent system: Researcher + Critic + Writer. Implement turn-based message passing', 'https://microsoft.github.io/autogen/docs/Getting-Started', "What coordination failure modes emerge in multi-agent systems that don't exist in single-agent?", 4, 'System', '3-agent coordination system', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 2: Agentic AI', 3, 20, 'Agent Safety & Guardrails', 'Add input/output guardrails, action confirmation, and rate limiting to your agent. Log all tool calls', 'https://docs.guardrailsai.com/', "What's the minimum viable safety layer for an agent acting on your behalf?", 4, 'System', 'Guardrails + rate limiting module', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 2: Agentic AI', 3, 21, 'Week 3 Review + Live Validation', "Write agent architecture doc with diagrams. Compare to AutoGPT/AutoGen design decisions. MICRO PROJECT: Ship 'Agent Trajectory Analyzer' — tool that replays agent runs, scores each step, and visualizes failure modes. LIVE VALIDATION: Post your ReAct agent demo (video + repo link) on Twitter/LinkedIn. Document every reaction, confusion, and question from strangers.", 'https://lilianweng.github.io/posts/2023-06-23-agent/', 'What did strangers misunderstand about your agent that you thought was obvious?', 2, 'Product', 'Agent Trajectory Analyzer tool + demo video', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 2: Agentic AI', 4, 22, 'LangGraph Introduction', 'Convert your ReAct agent to LangGraph. Implement cyclic graph with conditional edges', 'https://langchain-ai.github.io/langgraph/tutorials/introduction/', "What problems does a graph-based agent framework solve that chain-based doesn't?", 4, 'System', 'LangGraph agent with conditional edges', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 2: Agentic AI', 4, 23, 'Human-in-the-Loop', 'Add interrupt, approve, and modify nodes to your LangGraph agent. Test with 5 risky action scenarios', 'https://langchain-ai.github.io/langgraph/how-tos/human_in_the_loop/', 'At what granularity should human approval be required — task, step, or tool call?', 4, 'System', 'Human-in-the-loop interrupt nodes', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 2: Agentic AI', 4, 24, 'Agent State Management', 'Implement checkpointing and state rollback in LangGraph. Test recovery from mid-execution failures', 'https://langchain-ai.github.io/langgraph/how-tos/persistence/', 'How does agent state differ from application state in traditional software?', 4, 'Infra', 'Checkpoint + rollback state module', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 2: Agentic AI', 4, 25, 'Web Research Agent', 'Build a full web research agent: search → scrape → summarize → cite. Handle 10 research questions end-to-end', 'https://docs.tavily.com/docs/tavily-api/python-sdk', 'How do you prevent an agent from confidently citing hallucinated sources?', 4, 'System', 'Web research agent (search→scrape→cite)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 2: Agentic AI', 4, 26, 'Code Execution Agent', 'Build an agent that writes Python, executes it in a sandbox, reads output, and debugs. Test 10 coding tasks', 'https://e2b.dev/docs', 'What security boundaries must exist around an agent that can execute code?', 5, 'System', 'Code execution sandbox agent', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 2: Agentic AI', 4, 27, 'Agent Evaluation', 'Implement trajectory evaluation: score each step, not just final answer. Run 20 agent tasks, analyze failure modes', 'https://docs.smith.langchain.com/evaluation/tutorials/agents | https://arxiv.org/abs/2303.11366', 'What does a good agent trajectory look like vs a lucky one?', 4, 'Evaluation', 'Trajectory evaluation framework (20 tasks)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 2: Agentic AI', 4, 28, 'Week 4 Review + System Design', 'Record 3-minute agent walkthrough (RAG + web search + code execution). SYSTEM DESIGN CHALLENGE: Design a RAG SaaS — multi-tenant vector namespacing, rate limiting, cost-per-tenant tracking, horizontal scaling. Write 1-page architecture doc with explicit trade-off reasoning on stateless vs stateful components.', 'https://python.langchain.com/docs/use_cases/', "What's the gap between your agent demo and something you'd trust in production?", 3, 'Product', 'Agent walkthrough video + RAG SaaS architecture doc', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 3: Evaluation & Fine-tuning', 5, 29, 'RAGAS Framework', 'Run full RAGAS evaluation (faithfulness, answer relevancy, context precision) on your RAG pipeline. Score baseline', 'https://docs.ragas.io/en/stable/', 'Which RAGAS metric is hardest to improve and why?', 3, 'Evaluation', 'RAGAS baseline scores', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 3: Evaluation & Fine-tuning', 5, 30, 'LLM-as-Judge', 'Build a GPT-4 judge that scores answers on accuracy, completeness, and citation quality. Calibrate against human labels', 'https://arxiv.org/abs/2306.05685', 'What are the known biases of LLM-as-judge and how do you correct for them?', 4, 'Evaluation', 'GPT-4 judge module (3 scoring dimensions)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 3: Evaluation & Fine-tuning', 5, 31, 'Benchmark Dataset Creation', 'Create a 100-question eval set for your domain with gold answers. Use diverse question types', 'https://huggingface.co/docs/datasets/create_dataset', "How do you ensure your eval set isn't accidentally testing memorization?", 4, 'Evaluation', '100-question eval dataset', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 3: Evaluation & Fine-tuning', 5, 32, 'Fine-tuning Basics', 'Fine-tune a 7B model (Mistral/Llama) on 500 QA pairs using LoRA. Compare base vs fine-tuned on your eval set', 'https://huggingface.co/docs/trl/sft_trainer', 'When does fine-tuning help more than better prompting?', 5, 'Model', 'LoRA fine-tuned 7B model + comparison report', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 3: Evaluation & Fine-tuning', 5, 33, 'LoRA Deep Dive', 'Experiment with rank r=4,8,16,64. Plot eval score vs trainable parameters tradeoff', 'https://arxiv.org/abs/2106.09685', 'What does rank represent geometrically in LoRA adaptation?', 5, 'Model', 'LoRA rank sweep plot (r=4,8,16,64)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 3: Evaluation & Fine-tuning', 5, 34, 'Dataset Curation', 'Clean and filter your training data: dedup, quality filter, format normalize. Retrain and compare', 'https://huggingface.co/blog/data-measurements-tool', 'How much does data quality matter vs data quantity for fine-tuning?', 4, 'Model', 'Cleaned dataset + before/after comparison', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 3: Evaluation & Fine-tuning', 5, 35, 'Week 5 Review + Micro Project', "MICRO PROJECT: 'Evaluation Runner' — publish a public GitHub repo with your eval suite as a reusable CLI (run evals on any RAG pipeline via YAML config). Leaderboard: base model, RAG only, fine-tuned, fine-tuned+RAG — include 95% confidence intervals on all scores, not just point estimates. If your confidence intervals overlap, your result isn't significant.", 'https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard', 'Which combination wins and what does the confidence interval tell you about the reliability of that result?', 3, 'Product', 'Evaluation Runner CLI (public repo)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 3: Evaluation & Fine-tuning', 6, 36, '[STRETCH] DPO Training', 'Collect 200 preference pairs. Train DPO model. Compare to SFT model on helpfulness and safety', 'https://arxiv.org/abs/2305.18290 | https://arxiv.org/abs/2203.02155', 'What human preferences are hardest to capture in preference data?', 5, 'Model', '[STRETCH] DPO model + preference comparison', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 3: Evaluation & Fine-tuning', 6, 37, 'Hallucination Detection', 'Build a hallucination detector: NLI-based + self-consistency methods. Test on 50 known hallucinations', 'https://arxiv.org/abs/2303.08896', "What's the difference between confident hallucination and uncertain generation?", 5, 'Evaluation', 'Hallucination detector (NLI + self-consistency)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 3: Evaluation & Fine-tuning', 6, 38, 'Calibration + Applied Statistics', 'Measure model calibration (ECE) and implement temperature scaling. STATS TRACK: (1) Compute 95% confidence intervals on all your eval metrics using bootstrap sampling, (2) run A/B test between two RAG variants — check statistical significance (p<0.05) before claiming a winner, (3) build a calibration curve for your LLM-as-judge scores vs human labels, (4) understand when your eval sample size is too small to be trustworthy.', 'https://arxiv.org/abs/1706.04599 | https://arxiv.org/abs/2203.11171', 'When is a 3-point eval score improvement actually meaningful vs statistical noise?', 4, 'Evaluation', 'Calibration curve + bootstrap CI report', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 3: Evaluation & Fine-tuning', 6, 39, 'Adversarial Evaluation', 'Generate 50 adversarial prompts (jailbreaks, prompt injection, edge cases). Test and harden your pipeline', 'https://learnprompting.org/docs/prompt_hacking/intro', "What's the difference between a robust system and a brittle one that passes most tests?", 5, 'Evaluation', 'Adversarial eval set (50 prompts) + hardening report', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 3: Evaluation & Fine-tuning', 6, 40, 'Continuous Eval Pipeline', 'Build a CI eval pipeline using GitHub Actions: run eval suite on every commit, post results as PR comment', 'https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions', 'What would you add to this pipeline before trusting it for production decisions?', 4, 'Infra', 'GitHub Actions CI eval pipeline', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 3: Evaluation & Fine-tuning', 6, 41, 'Model Comparison Framework', 'Build a side-by-side comparison UI (Streamlit). Load 3 model variants, run same queries, display diffs', 'https://docs.streamlit.io/library/api-reference', 'What makes a fair comparison between models trained on different data?', 3, 'Product', 'Side-by-side model comparison UI (Streamlit)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 3: Evaluation & Fine-tuning', 6, 42, 'Week 6 Review + Live Validation', "MICRO PROJECT: 'LLM Cost Calculator' — public tool that takes model name, token counts, and query volume and outputs cost-per-query, cost-per-1M-queries, and break-even analysis for API vs self-hosted. Write technical blog post on 2-week fine-tuning learnings and publish on GitHub Pages. LIVE VALIDATION: Post both on GitHub + HN/Twitter. Log all feedback.", 'https://pages.github.com/', 'What do strangers find immediately useful vs what you thought was impressive?', 2, 'Product', 'LLM Cost Calculator tool + blog post', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 4: Production & Deployment', 7, 43, 'FastAPI Backend', 'Build a FastAPI backend for your RAG pipeline: /query, /ingest, /health endpoints. Add OpenAPI docs', 'https://fastapi.tiangolo.com/tutorial/', "What's the difference between designing a RAG API for internal use vs a public product?", 3, 'Infra', 'FastAPI RAG API (/query, /ingest, /health)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 4: Production & Deployment', 7, 44, 'Streaming Responses', 'Add SSE streaming to your FastAPI endpoint. Test latency improvement on long responses', 'https://fastapi.tiangolo.com/advanced/server-sent-events/', 'At what response length does streaming meaningfully improve perceived performance?', 3, 'Infra', 'SSE streaming endpoint', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 4: Production & Deployment', 7, 45, 'Caching Layer', 'Implement semantic caching using GPTCache or Redis. Measure cache hit rate and latency reduction on 1000 queries', 'https://gptcache.readthedocs.io/en/latest/', 'What queries should you never cache and why?', 4, 'Infra', 'Semantic caching layer + hit rate report', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 4: Production & Deployment', 7, 46, 'Docker & Containerization', 'Dockerize your full RAG + API stack. Write docker-compose.yml with model server, vector DB, API', 'https://docs.docker.com/get-started/', 'What configuration should never be hardcoded in a Docker image?', 3, 'Infra', 'Docker Compose stack (API + vector DB + model)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 4: Production & Deployment', 7, 47, 'Load Testing', 'Run Locust load test on your API: ramp to 100 concurrent users. Find the breaking point and fix it', 'https://docs.locust.io/en/stable/', "What's the first thing to optimize when your API breaks under load?", 4, 'Infra', 'Locust load test report (100 concurrent users)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 4: Production & Deployment', 7, 48, 'Observability', 'Add LangSmith tracing to every LLM call. Build a dashboard: P50/P99 latency, error rate, cost/query', 'https://docs.smith.langchain.com/observability', "What metric would you alert on in production that you didn't think to measure during dev?", 4, 'Infra', 'LangSmith dashboard (P50/P99, error rate, cost)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 4: Production & Deployment', 7, 49, 'Week 7 Review + System Design', 'Deploy stack to free tier (Render/Railway/Fly.io) — public URL, run 100 real queries, document every failure. SYSTEM DESIGN CHALLENGE: Design a multi-tenant AI platform. Answer explicitly: how do you isolate vector namespaces, share GPU compute fairly, handle bursty load, and price per-tenant? Write architecture doc + a cost model spreadsheet showing unit economics at 10, 1k, 100k users.', 'https://render.com/docs', "What broke in production that didn't break locally?", 3, 'Product', 'Deployed public URL + architecture doc + cost model', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 4: Production & Deployment', 8, 50, 'Authentication & Authorization', 'Add JWT auth to your API. Implement per-user document namespacing in the vector store', 'https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/', 'How does multi-tenancy in a RAG system differ from multi-tenancy in a traditional app?', 4, 'Infra', 'JWT auth + per-user vector namespacing', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 4: Production & Deployment', 8, 51, 'Cost Modeling + Optimization', 'Build a cost model spreadsheet covering: token economics (prompt vs completion cost per model), GPU cost tradeoffs (A10G vs A100 vs CPU for your workload), inference vs fine-tune cost curves, batch vs real-time serving tradeoffs. Then implement 3 pipeline optimizations to cut cost >30%. Deliverable: cost-per-query at 100/day, 10k/day, 1M/day — and the exact volume crossover where self-hosting beats API.', 'https://platform.openai.com/docs/guides/production-best-practices', 'At what query volume does switching from API to self-hosted model become cost-positive?', 4, 'Infra', 'Cost model spreadsheet + 3 optimizations', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 4: Production & Deployment', 8, 52, 'Async & Concurrency', 'Convert your pipeline to fully async. Benchmark throughput improvement vs sync version', 'https://fastapi.tiangolo.com/async/', 'When does async hurt rather than help?', 4, 'Infra', 'Async pipeline + throughput benchmark', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 4: Production & Deployment', 8, 53, 'Vector DB at Scale', 'Migrate from ChromaDB to Pinecone or Qdrant. Index 100k documents. Measure query time at scale', 'https://docs.pinecone.io/docs/overview', "What new failure modes appear at 100k documents that didn't exist at 1k?", 4, 'Infra', 'Scaled vector DB (100k docs) + query time report', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 4: Production & Deployment', 8, 54, 'CI/CD Pipeline', 'Build GitHub Actions pipeline: test → lint → build Docker image → deploy to staging → run eval → promote', 'https://docs.github.com/en/actions/use-cases-and-examples/deploying/about-continuous-deployment', "What's your minimum quality gate before allowing a deployment to production?", 4, 'Infra', 'CI/CD pipeline (test→build→deploy→eval)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 4: Production & Deployment', 8, 55, 'Monitoring & Alerting', 'Set up Prometheus + Grafana (or equivalent). Alert on: latency >2s, error rate >1%, cost spike >50%', 'https://prometheus.io/docs/introduction/overview/', "What's the difference between a metric that helps you debug vs one that helps you prevent?", 4, 'Infra', 'Prometheus + Grafana dashboard + drift detection alerts', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 4: Production & Deployment', 8, 56, 'Week 8 Review + Chaos Testing', 'CHAOS TESTING DAY: Deliberately break your system 4 ways: (1) kill vector DB mid-query, (2) mock LLM 30s timeout, (3) 50% random tool failure rate, (4) block GitHub API entirely. For each: measure degradation, verify graceful fallback, write a recovery SOP. Run 24h load test with monitoring. SYSTEM DESIGN CHALLENGE: Design a fault-tolerant agent workflow engine with retry policies and dead-letter queues.', 'https://sre.google/sre-book/table-of-contents/', 'Which failure mode was most dangerous and why had you not anticipated it?', 3, 'Infra', 'Chaos test report (4 failure scenarios) + recovery SOPs', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 5: Advanced Topics', 9, 57, 'GraphRAG', 'Implement knowledge graph extraction from documents. Build graph-enhanced retrieval and compare to vector-only', 'https://microsoft.github.io/graphrag/', 'What types of questions does graph retrieval answer that vector retrieval fundamentally cannot?', 5, 'System', 'GraphRAG module + comparison vs vector-only', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 5: Advanced Topics', 9, 58, 'Multimodal RAG', 'Add vision capability: ingest PDFs with images/tables. Answer questions that require reading charts', 'https://python.langchain.com/docs/use_cases/multi_modal/', 'How does grounding change when your evidence includes images?', 5, 'System', 'Multimodal RAG (PDF + images/tables)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 5: Advanced Topics', 9, 59, 'Long Context Models', 'Test Gemini 1.5 / Claude 3 on 100k token context. Compare to your chunked RAG on 10 long-doc tasks', 'https://arxiv.org/abs/2307.03172', 'When does chunked RAG outperform long-context models and why?', 5, 'Model', 'Long context vs chunked RAG comparison (10 tasks)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 5: Advanced Topics', 9, 60, 'Speculative Decoding', 'Implement speculative decoding with a draft model. Measure speedup on your inference pipeline', 'https://arxiv.org/abs/2211.17192', "What's the acceptance rate threshold below which speculative decoding hurts performance?", 5, 'Model', 'Speculative decoding module + speedup report', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 5: Advanced Topics', 9, 61, 'Distributed Systems for AI Engineers', 'Deep dive on: horizontal scaling, stateless vs stateful services, message queues (Redis Streams or RabbitMQ), event-driven architecture, backpressure design, idempotency, CAP theorem tradeoffs. BUILD: async document ingestion pipeline using Redis Streams — producer publishes docs, multiple consumer workers embed + upsert in parallel. Handle backpressure, retries with exponential backoff, duplicate suppression.', 'https://www.rabbitmq.com/tutorials/tutorial-one-python', "What happens to your AI system under bursty load if you don't design for backpressure?", 4, 'Distributed', 'Redis Streams async ingestion pipeline', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 5: Advanced Topics', 9, 62, '[STRETCH] Constitutional AI', 'Implement CAI critique-revision loop. Test on 20 harmful prompts. Measure safety vs helpfulness tradeoff', 'https://arxiv.org/abs/2212.08073', 'Is there a fundamental tradeoff between helpfulness and safety or is it a design choice?', 5, 'Model', '[STRETCH] CAI critique-revision module', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 5: Advanced Topics', 9, 63, 'Week 9 Review + Live Validation', "MICRO PROJECT: 'RAG Reliability Dashboard' — Streamlit app that visualizes retrieval failures, hallucination cases, confidence histograms, and latency outliers from your eval set. Push to public GitHub. LIVE VALIDATION: Post it on HN/Twitter and document all feedback. Write 1000-word deep dive on the advanced topic that surprised you most. SYSTEM DESIGN CHALLENGE: Design a streaming, fault-tolerant agent orchestration system.", 'https://arxiv.org/list/cs.CL/recent', 'What assumption did you hold for the past 9 weeks that turned out to be completely wrong?', 3, 'Product', 'RAG Reliability Dashboard (Streamlit) + deep dive blog', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 5: Advanced Topics', 10, 64, 'MiniGPT-Lite (Transformer from Scratch)', "Build MiniGPT-lite in 5-7 days max — this is for transformer intuition, not research: (1) BPE tokenizer from scratch on a small corpus, (2) tiny 2-layer transformer (128 dim, 4 heads, 512 context) in pure PyTorch — no HuggingFace, (3) train on TinyShakespeare dataset, (4) visualize attention weights per layer per head, (5) compare your learned token embeddings vs a pretrained model's embeddings on same vocabulary. Document what you can now see that you couldn't before.", 'https://github.com/karpathy/nanoGPT', 'What did building a transformer from scratch reveal that no paper or lecture ever made clear?', 4, 'Model', 'MiniGPT-Lite (2-layer transformer from scratch)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 5: Advanced Topics', 10, 65, '[STRETCH] Model Merging', 'Merge 3 fine-tuned models using TIES or DARE. Evaluate whether merged model retains all capabilities', 'https://arxiv.org/abs/2311.03099', 'What makes two models merge well vs catastrophically interfere?', 5, 'Model', '[STRETCH] 3-model merge + capability eval', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 5: Advanced Topics', 10, 66, 'Quantization', 'Quantize a 7B model to 4-bit GGUF using llama.cpp. Benchmark quality degradation at INT8, INT4, INT3', 'https://github.com/ggerganov/llama.cpp', 'At what quantization level does the model become unreliable for your use case?', 4, 'Model', 'Quantized model (INT8/INT4/INT3) + quality report', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 5: Advanced Topics', 10, 67, 'Inference Optimization', 'Profile inference bottlenecks with PyTorch profiler. Apply FlashAttention + KV cache. Measure TTFT and TPS', 'https://pytorch.org/tutorials/beginner/profiler.html', "What's the difference between optimizing for latency vs throughput?", 5, 'Model', 'Inference optimization report (FlashAttention + KV cache)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 5: Advanced Topics', 10, 68, 'Async Queue Ingestion Pipeline', 'Build a production-grade async document ingestion system using Celery + Redis: parallel chunk embedding workers, retries with exponential backoff, idempotency check (same doc hash = skip), priority queues (urgent vs bulk), dead-letter queue for poison docs. Load test: ingest 10k documents, measure throughput (docs/sec), find the bottleneck (CPU, network, or vector DB write), fix it, benchmark again.', 'https://docs.celeryq.dev/en/stable/getting-started/introduction.html', 'Where does the bottleneck shift as you scale from 1k to 100k documents?', 4, 'Distributed', 'Celery + Redis ingestion pipeline (10k docs)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 5: Advanced Topics', 10, 69, 'Interpretability', 'Use SHAP or activation patching to explain 10 model decisions. Find a case where the explanation is wrong', 'https://proceedings.neurips.cc/paper/2017/hash/8a20a8621978632d76c43dfd28b67767-Abstract.html', "What's the difference between an explanation that's correct and one that's useful?", 5, 'Model', 'Interpretability analysis (SHAP/activation patching)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 5: Advanced Topics', 10, 70, 'Week 10 Review + Determinism + System Design', "DETERMINISM AUDIT: Add seed control to all experiments. Run your full eval pipeline 5 times with different random seeds — measure run-to-run variance. If variance >2 points, your results aren't trustworthy; fix it (seed numpy, torch, Python random, FAISS). Build comparison matrix: all advanced techniques vs complexity, production-readiness, known failure modes. SYSTEM DESIGN CHALLENGE: Design an evaluation system that runs 10k eval cases per commit at sub-5-minute CI time.", 'https://paperswithcode.com/', 'Which of your previous eval results might be noise rather than signal?', 3, 'Evaluation', 'Determinism audit report + technique comparison matrix', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 11, 71, 'Capstone Scoping', 'Define capstone project: problem, dataset, success metrics, tech stack, timeline. Get spec reviewed (post on GitHub Issues)', 'https://github.com/PavanSiddapuram/Mentor_mastry', "What's the simplest version of this project that would still be impressive?", 3, 'Product', 'Capstone spec + success metrics', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 11, 72, 'Data Pipeline', 'Build production-grade ingestion pipeline: scrape/load → clean → chunk → embed → store. Handle 10k+ docs', 'https://docs.prefect.io/latest/', "What's your data pipeline's single point of failure?", 4, 'Infra', 'Production ingestion pipeline (10k+ docs)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 11, 73, 'Core RAG Implementation', 'Implement the core retrieval + generation pipeline for your capstone. All 3 retrieval strategies working', 'https://python.langchain.com/docs/', "What's different about building this the second time vs your Week 1 RAG?", 4, 'System', 'Core RAG implementation (3 retrieval strategies)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 11, 74, 'Agent Layer', 'Add agentic capabilities to capstone: tool use, multi-step reasoning, memory. Handle 20 complex queries', 'https://langchain-ai.github.io/langgraph/', 'Where does the agent help most vs where does it add unnecessary complexity?', 4, 'System', 'Agent layer with tools + memory', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 11, 75, 'Evaluation Suite', 'Build domain-specific eval suite: 50 questions with gold answers. Run automated eval on every commit', 'https://docs.ragas.io/', "How confident are you in your eval suite's ability to catch regressions?", 4, 'Evaluation', 'Domain-specific eval suite (50 questions)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 11, 76, 'UI / Interface', 'Build a Streamlit or Next.js frontend. Add: streaming, source citations, feedback buttons, conversation history', 'https://docs.streamlit.io/', 'What would a non-technical user find confusing about your interface?', 3, 'Product', 'Frontend UI (streaming + citations + feedback)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 11, 77, 'Week 11 Review', 'Internal demo: record a 5-minute walkthrough of the full capstone. List 5 known limitations honestly', 'https://github.com/PavanSiddapuram/Mentor_mastry', 'What would you need to build to make this genuinely useful to real users?', 3, 'Product', '5-minute walkthrough video + 5 known limitations', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 12, 78, 'Performance Hardening', 'Profile and optimize bottlenecks: target P99 latency <2s, cost <$0.01/query, 99% uptime', 'https://docs.locust.io/', 'What performance constraint matters most to your target user?', 4, 'Infra', 'Performance-hardened system (P99<2s, <$0.01/query)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 12, 79, 'Security & Abuse Hardening', "OWASP Top 10 audit on your API + AI-SPECIFIC SECURITY: (1) Prompt injection — test 20 known injection patterns, implement input sanitization + output validation layer, (2) Tenant isolation — cross-tenant leakage test: can user A retrieve user B's documents? Fix it, (3) Data exfiltration defense — rate limit + detect anomalous bulk retrieval, (4) Model abuse prevention — input length limits + topic classifier on inputs, (5) Forensic logging — log all prompts, retrieved chunks, and model outputs with session IDs for incident reconstruction.", 'https://owasp.org/www-project-top-ten/', "What's the difference between a prompt injection vulnerability and a logic bug — and why does it matter for how you fix them?", 4, 'Infra', 'Security audit report (OWASP + AI-specific)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 12, 80, 'Documentation', 'Write: README, API docs (OpenAPI), architecture diagram, deployment guide, known limitations', 'https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes', 'Who is your documentation written for and what do they need to succeed?', 3, 'Product', 'README + API docs + architecture diagram', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 12, 81, 'External Feedback', 'Share with 3 people outside your field. Document every piece of confusion they express. Fix the top 3', 'https://www.nngroup.com/articles/usability-testing-101/', 'What did you assume was obvious that turned out not to be?', 3, 'Product', 'User feedback report (3 external testers)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 12, 82, 'Blog Post Draft', "Write a detailed technical blog: problem, approach, key learnings, results, what you'd do differently", 'https://www.swyx.io/learn-in-public', "What's the most counterintuitive thing you learned that most people wouldn't expect?", 3, 'Product', 'Technical blog post draft', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 12, 83, 'Open Source Prep', 'Prepare repo for open source: license, contributing guide, issue templates, GitHub Actions, code cleanup', 'https://opensource.guide/starting-a-project/', 'What would make someone want to contribute to your project vs just use it?', 3, 'Product', 'Open source repo (license, contributing, CI)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 12, 84, 'Week 12 Review', 'Beta launch: post to Twitter/LinkedIn/HackerNews Show HN. Respond to every comment. Log feedback', 'https://news.ycombinator.com/showhn.html', "What's the gap between how you see your project and how strangers see it?", 3, 'Product', 'Beta launch post + feedback log', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 13, 85, 'Bug Fixes from Launch', 'Fix top 5 issues reported from beta launch. Each fix must have a test. Deploy hotfix', 'https://github.com/PavanSiddapuram/Mentor_mastry', 'What category of bug is most common — design, implementation, or assumption?', 3, 'Infra', '5 bug fixes with tests', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 13, 86, 'Stretch Feature', 'Ship one stretch feature you cut in Week 11. Must be fully tested and documented', 'https://github.com/PavanSiddapuram/Mentor_mastry', 'Why did you cut this feature originally and what changed?', 4, 'System', 'Stretch feature (tested + documented)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 13, 87, 'Final Benchmark Report', 'Run full eval suite one final time. Compare Day 1 RAG vs final capstone across all metrics', 'https://docs.ragas.io/', 'What metric improved most over 90 days and what drove that improvement?', 3, 'Evaluation', 'Final benchmark report (Day 1 vs Day 90)', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 13, 88, 'Portfolio Write-up', 'Update LinkedIn, resume, and GitHub profile. Add capstone as featured project with quantified results', 'https://www.linkedin.com/', 'How would you explain what you built in 30 seconds to a non-technical person?', 2, 'Product', 'Updated LinkedIn + resume + featured project', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 13, 89, 'Retrospective', "Write a 1000-word 90-day retrospective: what worked, what didn't, what you'd do differently, what's next", 'https://github.com/PavanSiddapuram/Mentor_mastry', 'What version of yourself started this sprint and who is finishing it?', 2, 'Product', '1000-word retrospective', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
    ['Phase 6: Capstone', 13, 90, 'Day 90 — Graduation', 'Present capstone to at least one technical person. Record the feedback. Plan the next 90 days', 'https://github.com/PavanSiddapuram/Mentor_mastry', 'What would you tackle in a second 90-day sprint?', 2, 'Product', 'Capstone presentation + next 90-day plan', 'Pending', '', '', 0, '', '', '', '', '', '', ''],
]

META_HEADERS = ["Key", "Value"]
META_ROWS = [
    ["current_streak", "0"],
    ["last_completed_day", "0"],
    ["consecutive_missed", "0"],
]


def main():
    print("Authenticating with Google...")
    creds = get_credentials()
    client = gspread.authorize(creds)

    print(f"Opening sheet: {SHEET_ID}")
    spreadsheet = client.open_by_key(SHEET_ID)

    # ── Main tab ──────────────────────────────────────────────────────────────
    existing_titles = [ws.title for ws in spreadsheet.worksheets()]
    print(f"Existing tabs: {existing_titles}")

    if "90_Day_Master_Plan" not in existing_titles:
        # If Sheet1 or similar default exists, rename it; else create new
        if existing_titles:
            ws = spreadsheet.get_worksheet(0)
            ws.update_title("90_Day_Master_Plan")
            print("Renamed first tab to '90_Day_Master_Plan'")
        else:
            ws = spreadsheet.add_worksheet("90_Day_Master_Plan", rows=100, cols=21)
            print("Created '90_Day_Master_Plan' tab")
    else:
        ws = spreadsheet.worksheet("90_Day_Master_Plan")
        print("Found existing '90_Day_Master_Plan' tab")

    # Write headers + all 90 rows
    all_rows = [HEADERS] + [list(map(str, row)) for row in CURRICULUM]
    ws.clear()
    ws.update(values=all_rows, range_name="A1", value_input_option="USER_ENTERED")
    print(f"✅ Written {len(CURRICULUM)} curriculum rows to '90_Day_Master_Plan'")

    # Bold the header row
    ws.format("A1:U1", {"textFormat": {"bold": True}})

    # ── Meta tab ──────────────────────────────────────────────────────────────
    if "meta" not in existing_titles:
        meta_ws = spreadsheet.add_worksheet("meta", rows=10, cols=2)
        print("Created 'meta' tab")
    else:
        meta_ws = spreadsheet.worksheet("meta")
        print("Found existing 'meta' tab")

    meta_all = [META_HEADERS] + META_ROWS
    meta_ws.clear()
    meta_ws.update(values=meta_all, range_name="A1", value_input_option="USER_ENTERED")
    meta_ws.format("A1:B1", {"textFormat": {"bold": True}})
    print("✅ Written meta tab (current_streak=0, last_completed_day=0, consecutive_missed=0)")

    print("\n🎉 Sheet fully populated! Run the morning test next:")
    print("   python execution/mentor_scheduler.py --test morning")


if __name__ == "__main__":
    main()
